version: 1

# =========================================================
# REQUIRED PATHS
# =========================================================
required_paths:

  # ---------- VALID ----------
  - absdef/
  - app/
  - bs_cfg/
  - build/
  - cfg/
  - design/
  - docs/
  - node_modules/
  - s32k344-freertos/
  - s32k344-mcal/
  - src/
  - temp/
  - tests/
  - .clang-format
  - .gitattributes
  - .gitignore
  - .gitmodules
  - .releasefilelist
  - build.log
  - clean-up.bat
  - cmake-build.bat
  - CMakeLists.txt
  - CMakePresets.json
  - README.md


  # ---------- INVALID DUMMY CASES----------
  - dummy_path/
  - dummy_file.txt

